// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: analyser.proto

package analyser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnalyseRequest is the request the Analyse endpoint accepts.
type AnalyseUserAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A user agent string from an HTTP request
	UserAgent string `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
}

func (x *AnalyseUserAgentRequest) Reset() {
	*x = AnalyseUserAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analyser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyseUserAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseUserAgentRequest) ProtoMessage() {}

func (x *AnalyseUserAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseUserAgentRequest.ProtoReflect.Descriptor instead.
func (*AnalyseUserAgentRequest) Descriptor() ([]byte, []int) {
	return file_analyser_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyseUserAgentRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// AnalyseResponse is the response returned from the Analyse endpoint, containing information about
// the analysis result from the user agent string.
type AnalyseUserAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The browser contained in the user agent string
	Browser string `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
}

func (x *AnalyseUserAgentResponse) Reset() {
	*x = AnalyseUserAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analyser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyseUserAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseUserAgentResponse) ProtoMessage() {}

func (x *AnalyseUserAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseUserAgentResponse.ProtoReflect.Descriptor instead.
func (*AnalyseUserAgentResponse) Descriptor() ([]byte, []int) {
	return file_analyser_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyseUserAgentResponse) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

var File_analyser_proto protoreflect.FileDescriptor

var file_analyser_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x17, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x22, 0x34, 0x0a, 0x18, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x32, 0x67, 0x0a, 0x08, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x12, 0x5b, 0x0a, 0x10, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x61, 0x6e, 0x61,
	0x6c, 0x79, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x61, 0x6e, 0x6e, 0x69, 0x2d, 0x70, 0x6f, 0x70, 0x6f, 0x76, 0x61, 0x2f, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_analyser_proto_rawDescOnce sync.Once
	file_analyser_proto_rawDescData = file_analyser_proto_rawDesc
)

func file_analyser_proto_rawDescGZIP() []byte {
	file_analyser_proto_rawDescOnce.Do(func() {
		file_analyser_proto_rawDescData = protoimpl.X.CompressGZIP(file_analyser_proto_rawDescData)
	})
	return file_analyser_proto_rawDescData
}

var file_analyser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_analyser_proto_goTypes = []interface{}{
	(*AnalyseUserAgentRequest)(nil),  // 0: analyser.AnalyseUserAgentRequest
	(*AnalyseUserAgentResponse)(nil), // 1: analyser.AnalyseUserAgentResponse
}
var file_analyser_proto_depIdxs = []int32{
	0, // 0: analyser.Analyser.AnalyseUserAgent:input_type -> analyser.AnalyseUserAgentRequest
	1, // 1: analyser.Analyser.AnalyseUserAgent:output_type -> analyser.AnalyseUserAgentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analyser_proto_init() }
func file_analyser_proto_init() {
	if File_analyser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_analyser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyseUserAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analyser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyseUserAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_analyser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analyser_proto_goTypes,
		DependencyIndexes: file_analyser_proto_depIdxs,
		MessageInfos:      file_analyser_proto_msgTypes,
	}.Build()
	File_analyser_proto = out.File
	file_analyser_proto_rawDesc = nil
	file_analyser_proto_goTypes = nil
	file_analyser_proto_depIdxs = nil
}
